### ISSUE TITLE
Connect SSP file reader to web display

### ISSUE THREAD

**Issue by piphamilton** [DUNE-DAQ/dqm-backend#1]
Plots produced by the SSP HDF5 file reader script need to be transmitted and available for display alongside the charge information currently available.

**Comment by dingp** [comment]
Could this issue be closed or deferred to `3.0` release?

**Comment by jmcarcell** [comment]
Done

**Comment by glehmannmiotto** [comment]
I suggest to drop this. we are never going to have SSP data anymore...
